### PR TITLE
fix(StyleObserver): convert camelCase properties to kebab-case

### LINKED ISSUE #523: Binding style object works only on single worded css properties [1.0.9]
I have an element with css.bind="style".
In Viewmodel I have:
```
	get style() {
		return {
			backgroundColor: blabla,
			color: blabla,
			padding: blabla,
			fontFamily: blabla,
			fontWeight: blabla,
			fontStyle: blabla,
			fontSize: blabla,
			textAlign: blabla
		};
	}
```

But only color and padding gets binded. I just assume its because other properties are not single words.
Previously I used version 1.0.4 and everything worked fine.

### PR DESCRIPTION
**Pull request by z-brooks**
The property methods (`set|removeProperty`) don't recognize _camelCased_ names.

fixes #523

### CODE REVIEW

File: src/element-observation.js [hunk 1]
```diff
@@ -70,17 +70,24 @@ export class StyleObserver {
...
     let style;
     let version = this.version;
 
     if (newValue !== null && newValue !== undefined) {
       if (newValue instanceof Object) {
+        let value;
         for (style in newValue) {
           if (newValue.hasOwnProperty(style)) {
+            value = newValue[style];
+            style = style.replace(/([A-Z])/g, this._fixCase);
```
Comment (jdanyow) [inline src/element-observation.js]: @z-brooks what do you think about changing this to `.replace(...., m => '-' + m.toLowerCase());` instead of using the class method?

Comment (z-brooks) [inline src/element-observation.js]: @jdanyow  Yeah, that's fine. I had originally done that but I wasn't sure and thought closures and the like were discouraged.

Comment (jdanyow) [inline src/element-observation.js]: thanks for changing that- arrow functions are ok- it's only a closure if it accesses the outer scope.
